services:
  airflow-init:
    build:
      context: ../../../
      dockerfile: ./src/mle_hw5_package/batch_inference/Dockerfile
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/src/mle_hw5_package/batch_inference
    volumes:
      - ../../../airflow-data:/opt/airflow
      - ../../../data/inference_images:/opt/airflow/data/inference_images
      - ../../../models:/opt/airflow/models
      - ../:/opt/airflow/src/mle_hw5_package
      - ../../../batch_predictions:/opt/airflow/batch_predictions
    command: db migrate
    restart: "no"

  airflow-webserver:
    build:
      context: ../../../
      dockerfile: ./src/mle_hw5_package/batch_inference/Dockerfile
    restart: always
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/src/mle_hw5_package/batch_inference
      - LOAD_EX=n
    ports:
      - "8080:8080"
    volumes:
      - ../../../airflow-data:/opt/airflow
      - ../../../data/inference_images:/opt/airflow/data/inference_images
      - ../../../models:/opt/airflow/models
      - ../:/opt/airflow/src/mle_hw5_package
      - ../../../batch_predictions:/opt/airflow/batch_predictions
    command: webserver

  airflow-scheduler:
    build:
      context: ../../../
      dockerfile: ./src/mle_hw5_package/batch_inference/Dockerfile
    restart: always
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/src/mle_hw5_package/batch_inference
    volumes:
      - ../../../airflow-data:/opt/airflow
      - ../../../data/inference_images:/opt/airflow/data/inference_images
      - ../../../models:/opt/airflow/models
      - ../:/opt/airflow/src/mle_hw5_package
      - ../../../batch_predictions:/opt/airflow/batch_predictions
    command: scheduler

volumes:
  airflow-data: