version: '3'
services:
  airflow-init:
    build:
      context: .
      dockerfile: ./dags/Dockerfile
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
    volumes:
      - ./airflow-data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./config:/opt/airflow/config
    command: db migrate
    restart: "no"

  airflow-webserver:
    build:
      context: .
      dockerfile: ./dags/Dockerfile
    restart: always
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - LOAD_EX=n
    ports:
      - "8080:8080"
    volumes:
      - ./airflow-data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./config:/opt/airflow/config
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: ./dags/Dockerfile
    restart: always
    depends_on:
      - airflow-init
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
    volumes:
      - ./airflow-data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./config:/opt/airflow/config
    command: scheduler

volumes:
  airflow-data:
