# docker-compose.yml
version: '3.8'
services:
  mlflow-server:
    build: ./mlflow/server
    ports:
      - "5001:5000"
    volumes:
      - "mlflow-data:/mlflow"
      - "./mlflow/artifacts:/mlflow/artifacts"
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow/db/mlflow.db
      - MLFLOW_ARTIFACT_URI=/mlflow/artifacts
  
  mlflow-client:
    build: 
      context: .
      dockerfile: ./mlflow/client/Dockerfile
      args:
        EXPERIMENT_NUMBER: ${EXPERIMENT_NUMBER}
    depends_on:
      - mlflow-server
    volumes:
      - "mlflow-data:/mlflow"
      - "./mlflow/artifacts:/mlflow/artifacts"
    environment:
      - EXPERIMENT_NUMBER=${EXPERIMENT_NUMBER}
  
volumes:
  mlflow-data: {}
