# docker-compose.yml
version: '3.8'
services:
  mlflow-server:
    build: ./mlflow-server
    ports:
      - "5001:5000"
    volumes:
      - "mlflow-data:/mlflow"
  
  mlflow-client:
    build: 
      context: .
      dockerfile: ./mlflow-client/Dockerfile
      args:
        EXPERIMENT_NUMBER: ${EXPERIMENT_NUMBER}
    depends_on:
      - mlflow-server
    volumes:
      - "mlflow-data:/mlflow"
    environment:
      - EXPERIMENT_NUMBER=${EXPERIMENT_NUMBER}
  
volumes:
  mlflow-data: {}
