version: '3.8'
services:
  server:
    build: 
      context: ../../../
      dockerfile: ./src/mle_hw5_package/online_inference/server/Dockerfile
    ports:
      - "1234:1234"
    volumes:
      - ../../../:/app  # Reflect the entire project inside /app in the container

  client:
    build:
      context: ../../../
      dockerfile: ./src/mle_hw5_package/online_inference/client/Dockerfile
      args:
        IMAGE_PATH: ${IMAGE_PATH:-"yes/Y19.jpg"}
    depends_on:
      - server
    environment:
      - IMAGE_PATH=${IMAGE_PATH}
