name: sentiment-analysis
on: [push]
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - uses: iterative/setup-cml@v1
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc pull
          dvc repro 
          git config --global --add safe.directory '*'

          git fetch --prune
          BASE_BRANCH=$(git merge-base origin/main HEAD)
          dvc metrics diff --md $BASE_BRANCH > report.md

          # Add figure to the report
          echo "## Confusion matrix" >> report.md
          cml-publish metrics/confusion_matrix.png --md >> report.md
          cml comment create report.md